"""empty message

Revision ID: ab9558a8cc3e
Revises: 83d7d9b56a03
Create Date: 2026-07-10 20:43:11.072568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9558a8cc3e'
down_revision: Union[str, Sequence[str], None] = '83d7d9b56a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comment_card_id', 'comments', ['card_id'], unique=False)
    op.create_index('ix_list_board_id_position', 'lists', ['board_id', 'position'], unique=False)
    op.create_index('ix_notification_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_index('ix_notification_user_id_created_at', table_name='notifications')
    op.drop_index('ix_list_board_id_position', table_name='lists')
    op.drop_index('ix_comment_card_id', table_name='comments')
    # ### end Alembic commands ###
